[BITS 16]
    %include 'source/menu.asm'
    %include 'source/pmode.asm'
[BITS 32]
    %include 'source/solleros.asm'
    %include 'source/programs.asm'
    %include 'source/batchprogs.asm'
    %include 'source/ps2mouse.asm'
    %include 'source/ints.asm'
    %include 'source/gui.asm'
    %include 'source/network.asm'
    %include 'source/disk.asm'
    %include 'source/msg.asm'
    %include 'files.asm'