[BITS 16]
    %include 'Free\menu.asm'
    %include 'Free\pmode.asm'
[BITS 32]
    %include 'Free\solleros.asm'
    %include 'Free\programs.asm'
    %include 'Free\batchprogs.asm'
    %include 'Free\userprogs.asm'
    %include 'Other\ps2mouse.asm'
    %include 'Free\ints.asm'
    %include 'Free\graphical.asm'
    %include 'Free\gui.asm'
    %include 'Free\network.asm'
    %include 'Free\msg.asm'
